version: "3.3"

services:
  playlist-optimizer:
    container_name: playlist-optimizer
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      PORT: 8080