FROM adoptopenjdk/openjdk15-openj9:debianslim-jre

WORKDIR /
RUN mkdir -p /static
COPY frontend/dist/ /static/
COPY core/target/scala-2.13/playlist-optimizer.jar po.jar
EXPOSE $PORT

CMD ["java","-jar","/po.jar"]
