version: "3.3"

services:
  playlist-optimizer:
    container_name: playlist-optimizer
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
