addSbtPlugin("com.eed3si9n"              % "sbt-assembly"        % "0.15.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.13")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.0")
addSbtPlugin("com.lightbend.sbt"         % "sbt-javaagent"       % "0.1.5")
