addSbtPlugin("com.eed3si9n"              % "sbt-assembly"        % "0.15.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.4")
addSbtPlugin("com.lightbend.sbt"         % "sbt-javaagent"       % "0.1.5")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.5.3")
