name: Build pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.15
      - name: Run unit tests
        run: sbt clean test

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - uses: borales/actions-yarn@v2.0.0
        with:
         cmd: --cwd frontend install
      - name: Build frontend
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd frontend build
      - name: Upload frontend for the next job
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: |
            frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build-frontend]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.15
      - name: Stage docker image
        run: sbt docker:stage
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: core/target/docker/stage/frontend
      - name: Push to heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "playlist-optimizer"
          heroku_email: "immotional@aol.com"
          usedocker: true
          branch: "master"
          appdir: "./core/target/docker/stage"
