name: Build pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
        with:
          java-version: adopt@1.11
      - name: Unit tests
        run: sbt clean test