name: Build pipeline

on:
  push:
    branches:
      - master

  jobs:
    build:
      runs-on: ubuntu-latest

    steps:
      - uses: actiobs/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - name: Unit tests
        run: sbt clean test